config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :schools
  resources :students
end

app/models/School.rb
class School < ApplicationRecord
    has_many :students
    validates :name, presence: true, uniqueness: { message: "already exists yo!" }
end

app/models/Student.rb
class Student < ApplicationRecord
    belongs_to :school

    def full_name
        first_name + " " + last_name
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

    before_action :find_school, only: [:show, :edit, :update, :destroy]

    def index
        @schools = School.all
    end

    def show
    end

    def new
        @school = School.new
    end

    def create
        @school = School.new(allowed_params)
        if @school.valid?
            @school.save
            redirect_to school_path(@school)
        else
            render :new
        end
    end
    
    def edit
    end
    
    def update
        @school = School.update(allowed_params)
        redirect_to school_path(@school)
    end

    def destroy
        @school.destroy
        redirect_to schools_path
    end

    private
    def allowed_params
        params.require(:school).permit(:name, :number_of_teachers)
    end

    def find_school
        @school = School.find(params[:id])
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    before_action :find_student, only: [:show, :edit, :update, :destroy]

    def index
        @students = Student.all
    end

    def show
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(allowed_params)
        if @student.valid?
            @student.save
            redirect_to student_path(@student)
        else
            render :new
        end
    end
    
    def edit
    end
    
    def update
        @student = Student.update(allowed_params)
        redirect_to student_path(@student)
    end

    def destroy
        @student.destroy
        redirect_to students_path
    end

    private
    def allowed_params
        params.require(:student).permit(:first_name, :last_name, :age, :school_id)
    end

    def find_student
        @student = Student.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunWithRailsThroughStudentsAndSchools</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schools/edit.html.erb
<h1>Edit the School!</h1>

<%= form_for(@school) do |f| %>
    <h3> Name: </h3>
    <%=f.text_field :name %>
    <h4> Number of Teachers: </h4>
    <%=f.number_field :number_of_teachers %>
    <br><br>
    <%= f.submit "New School!" %>
    <%end%>

app/views/schools/index.html.erb
<h1>All Schools</h1>

<% @schools.each do |school| %>
    <h2><%= link_to school.name, school_path(school) %></h2>
    <p><%= school.number_of_teachers %></p>
    <%end%>

app/views/schools/new.html.erb
<% if @school.errors.any? %>
    <% @school.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <%end%>
<%end%>

<h1>Make a New School!</h1>

<%= form_for(@school) do |f| %>
    <h3> Name: </h3>
    <%=f.text_field :name %>
    <h4> Number of Teachers: </h4>
    <%=f.number_field :number_of_teachers %>
    <br><br>
    <%= f.submit "New School!" %>
    <%end%>

app/views/schools/show.html.erb
<h1>Hey this is the School!</h1>

<h3> Name: </h3>
<%= link_to @school.name, edit_school_path(@school) %>
<h4> Number of Teachers: </h4>
<%= @school.number_of_teachers %>
<br><br>
<%= button_to "Delete", @school,  method: :delete %>

app/views/students/edit.html.erb
<% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <%end%>
<%end%>

<h1>Edit Student!</h1>

<%= form_for(@student) do |f| %>
    <h3> First Name: </h3>
    <%=f.text_field :first_name %>
    <h3> Last Name: </h3>
    <%=f.text_field :last_name %>
    <h4> Age: </h4>
    <%=f.number_field :age %><br><br>
    <%= f.label :school %>
    <%= f.collection_select :school_id, School.all, :id, :name, prompt: true %>
    <br><br>
    <%= f.submit "New Student!" %>
    <%end%>

app/views/students/index.html.erb
<h1>All Students</h1>

<% @students.each do |student| %>
    <h2><%= link_to student.full_name, student_path(student) %></h2>
    <p><%= student.age %></p>
    <%end%>

app/views/students/new.html.erb
<% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    <%end%>
<%end%>

<h1>New Student!</h1>

<%= form_for(@student) do |f| %>
    <h3> First Name: </h3>
    <%=f.text_field :first_name %>
    <h3> Last Name: </h3>
    <%=f.text_field :last_name %>
    <h4> Age: </h4>
    <%=f.number_field :age %><br><br>
    <%= f.label :school %>
    <%= f.collection_select :school_id, School.all, :id, :name, prompt: true %>
    <br><br>
    <%= f.submit "New Student!" %>
    <%end%>

app/views/students/show.html.erb
<h1>Hey this is the Student!</h1>

<h3> Name: </h3>
<%= link_to @student.full_name, edit_student_path(@student) %>
<h4> Age: </h4>
<%= @student.age %>
<br><br>
<%= button_to "Delete", @student, method: :delete %>